packages:
  - .
  - apps/*

updateConfig:
  ignoreDependencies:
    - typescript

publicHoistPattern:
  - '@intlify/*'
  - vue-i18n

overrides:
  '@tiptap/core@>=3.7.0 <3.30.5': 3.31.4
  '@tiptap/pm@>=3.7.0 <3.31.3': 3.31.4
  'axios@<1.20.0': 1.20.0
  'brace-expansion@<1.1.21': 1.1.21
  'brace-expansion@>=2.0.0 <2.1.7': 2.1.7
  'brace-expansion@>=4.0.0 <5.0.12': 5.0.12
  'devalue@<=5.9.2': 5.9.3
  'deepmerge-ts@<8.0.0': 8.0.0
  'esbuild@>=0.27.3 <0.28.1': 0.28.2
  'fast-uri@>=3.0.0 <3.1.8': 3.1.8
  'js-yaml@>=3.0.0 <3.15.2': 3.15.2
  'multer@<2.3.0': 2.3.0
  'mysql2@<=3.23.0': 3.23.1
  'nx>smol-toml': 1.7.1
  'serialize-javascript@>=7.1.1 <7.1.2': 7.1.2
  'vitepress>vite': 6.4.3

allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@prisma/engines': true
  bcrypt: true
  unrs-resolver: false
  nx: true
  prisma: true
  esbuild: true
  vue-demi: false
  msgpackr-extract: false
  workerd: false

minimumReleaseAgeExclude:
  - '@rollup/*'
  - autoprefixer@10.6.0
  - enhanced-resolve@5.25.0
  - '@nestjs/common@12.1.0'
  - '@nestjs/core@12.1.0'
  - '@nestjs/platform-express@12.1.0'
  - '@nestjs/testing@12.1.0'
  - '@prisma/adapter-pg@7.10.0'
  - '@prisma/client-runtime-utils@7.10.0'
  - '@prisma/client@7.10.0'
  - '@prisma/debug@7.10.0'
  - '@prisma/driver-adapter-utils@7.10.0'
  - '@prisma/config@7.10.0'
  - '@prisma/engines@7.10.0'
  - '@prisma/fetch-engine@7.10.0'
  - '@prisma/get-platform@7.10.0'
  - '@querry-kit/*'
  - prisma@7.10.0
  - rollup@4.63.2
  - yaml@2.9.1

patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
  node-forge@1.4.0: patches/node-forge@1.4.0.patch
